### ISSUE TITLE
Please provide a non-minimized version

### ISSUE THREAD

**Issue by Quix0r** [guerrerocarlos/CacheP2P#15]
A minimized version is good for performance (much lesser code to load) but harder for humans to read (+ understand consequently). Please consider providing a non-minimized version and maybe use some OpenSource tool to build the minimized version (it should be ignored in .gitignore then as everybody can build it on their own).

**Comment by DanielSidhion** [comment]
The non-minimized version is the `index.js` file. If you look at `package.json`, you'll notice that the "build" script is the one that actually generates the minimized version (using open source tools). I don't know why the minimized version is also included in the git repository, but this shouldn't be a problem, as you'll mostly ignore it and work in the `index.js` file.

**Comment by Quix0r** [comment]
Ah, okay. I was not aware of it. Sorry fot the noise. :-)

**Comment by deckar01** [comment]
I have seen projects that prefer a webpacked, but not minified release. They want to be able to audit the final script without having to build it manually.
