### ISSUE TITLE
Refresh cache

### ISSUE THREAD

**Issue by goatandsheep** [guerrerocarlos/CacheP2P#2]
How do you change the content on the page?
What if someone caches your URLs with malicious scripts before you have the opportunity to claim the magnet link?

**Comment by guerrerocarlos** [comment]
In the [documentation](http://www.cachep2p.com/documentation.html) steps 2 and 3 you can decide when existing Caches are no longer valid. Also if someone add malicious scripts that cache will also not be valid because of the verification sha will not be the same.

**Comment by Quix0r** [comment]
Remember that **dynamically** generated pages cannot be cached due to their nature (that they are dynamically generated and their content may change every time you call it).
