### ISSUE TITLE
homepage of CacheP2P

### ISSUE THREAD

**Issue by extend1994** [guerrerocarlos/CacheP2P#24]
Hi,
I am a member of cdnjs,
to add the library correctly,
I want to confirm that whether the url `https://cachep2p.com` presented in `homepage` and `author/url` in `package.json` is not working anymore?
Should it just be `http://cachep2p.com` which is not `https`?

thank you!

**Comment by guerrerocarlos** [comment]
Hello @extend1994 yes, the url was down because of the ssl certificate had expired, but it's fixed now. Thanks for the heads up!

So you can now leave https://cachep2p.com/ without problem.
