### ISSUE TITLE
Security hashes are not verified when receiving files

### ISSUE THREAD

**Issue by DanielSidhion** [guerrerocarlos/CacheP2P#7]
There is no check in the current code that verifies the security hash of a received file against the hash in `document.security_sha1`.

This allows anyone to serve a hijacked page for a given URL, and is a **critical** security problem.

I have attached 3 files to demonstrate the problem:
[entry.txt](https://github.com/guerrerocarlos/CacheP2P/files/545119/entry.txt)
[vulnerable.hijacked.txt](https://github.com/guerrerocarlos/CacheP2P/files/545121/vulnerable.hijacked.txt)
[vulnerable.txt](https://github.com/guerrerocarlos/CacheP2P/files/545120/vulnerable.txt)

Steps to reproduce:
1) Put those files in a directory with the current cachep2p.min.js and rename them from "_.txt" to "_.html" (github wouldn't let me attach htmls)
2) Edit the links and hashes in all 3 pages according to the hashes of `entry.html` and `vulnerable.html` (just as the documentation instructs you to)
3) Open two tabs in your browser (I did it with one tab in "normal" mode and the other in incognito mode)
4) In one of the tabs, navigate to the `entry.html` page. It will begin seeking for a peer with the `vulnerable.html` page
5) In your file system, rename `vulnerable.html` to something like `vulnerable.original.html`, then rename `vulnerable.hijacked.html` to `vulnerable.html`
6) In the other tab, open now the `vulnerable.html` page (which should be the hijacked version). It will serve this hijacked version of the page to the other tab
7) Check your console logs in the first tab (the one with `entry.html`). As soon as the page receives a cached version of `vulnerable.html`, click the link
8) Verify that it goes to the hijacked page. Also verify that the `security_sha1` of this page is different from the hash you obtained when setting up the pages.

**Comment by guerrerocarlos** [comment]
That is true, security it still has to be enabled. 

Only requires a few lines to do it, checking the checksum of the cache with the **security_sha1** object inside the **onTorrent** function, the question is, what to do after that happens? put that user in a blacklist and ask for that content again? the contributors are welcome to define this 👍  

Will add the bug label to it.

**Comment by DanielSidhion** [comment]
I believe it was very wrong of you to have put in CacheP2P's website that it does verify security hashes without actually doing so (or at least warning users it was still WIP). This is a very important issue, because anyone who would want to try the project could expose their users to basically any code execution an attacker would like to run (not to mention phishing attempts).

I'll leave the decision to you of what CacheP2P should do when it encounters a file with a different security hash than specified, but I think we could agree that the simplest case would be to just drop the received file and not try again, i.e. just hit the servers again when the user clicks a link.

I have opened a PR which does just that, thus fixing this issue. Please consider merging it to avoid exposing early enthusiasts. You can change its behavior later. CacheP2P is a very interesting idea, but it could be misused for evil if security is not taken seriously during development.

**Comment by guerrerocarlos** [comment]
Very important and it's very nice to receive the first pull request, merged and added right away. Updated npm and the published libraries.

**Comment by guerrerocarlos** [comment]
Changed the message since the hash can be invalid but not necessarily malicious, since it is used for invalidating old caches, it can just be receiving an old cache of a page that was updated.

**Comment by guerrerocarlos** [comment]
Checked and there is a way to add the **bad IP** to a  **blacklist** in webtorrent, so the solution would be to kill the current webtorrent client, update the blacklist (webtorrent currently doesn't have a direct way to do it, only through an external url to load the blacklist from), and create a new client instance that will not connect to the bad Cache emisor IP. 

Also would need to add to webtorrent a way to track the peers IPs that delivered the content and add it to the resulting torrent object, right now it is not included, so no way to know the IP where it came from.

For the moment, it will just disable that url from being cached and the link will not be updated to use that bad-hash cache, asuming it is just because of an updated page that made all previous caches no longer valid, they should die over time and new caches with the correct hash should be created automatically over time.

**Comment by DanielSidhion** [comment]
Great! Thank you for being quick on this.

Should that be the case of opening a feature request (and possibly a PR) to the webtorrent project? I believe it would be nice to be able to dynamically change the blacklist (without killing and reopening the webtorrent client).

**Comment by guerrerocarlos** [comment]
Yes, a PR would be the best for adding the 'on the fly' change to the blacklist, and would be the ideal solution.

**Comment by deckar01** [comment]
> Should that be the case of opening a feature request (and possibly a PR) to the webtorrent project?

WebTorrent should already verify the contents of torrents. I think this issue was caused by the custom fork of WebTorrent deviating from the BitTorrent protocol. See #14.
