### ISSUE TITLE
CacheP2P functionality

### ISSUE THREAD

**Issue by ipranjal** [guerrerocarlos/CacheP2P#9]
Does p2p network servers the JavaScript also ? And how does it Handel dynamic pages ?

**Comment by guerrerocarlos** [comment]
CacheP2P, only handles what's in  document.documentElement.innerHTML, so only the HTML as received, and already has a mechanism for embedding CSS if it is wanted.

The JS files could also be embedded into the Cache document, but that functionality would need to be added.

**Comment by guerrerocarlos** [comment]
Dynamic pages are Cached as received, so they can be handled by modifying the security hash of each page as it is updated, making all previous cache no longer valid, and only the new version of the page the valid one.

**Comment by ipranjal** [comment]
Thanks man !  Awesome project I appreciate your efforts _highfive_
